@startuml aws-architecture

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/ApplicationIntegration/EventBridgeScheduler.puml
!include AWSPuml/ApplicationIntegration/SimpleNotificationService.puml
!include AWSPuml/ApplicationIntegration/SimpleNotificationServiceEmailNotification.puml

left to right direction

EventBridgeScheduler(scheduler, "Scheduler", "Trigger Lambda every minute")
Lambda(execute_check, "ExecuteCheckFunction", "Run all tracker-queries from DynamoDB")
DynamoDB(db, "GymClassTrackerTable", "Hold status for all tracker-queries")

SimpleNotificationService(sns, "GymSNSTopic", "")
SimpleNotificationServiceEmailNotification(sns_email, "SNSEmailSubscription", "")

scheduler --> execute_check: trigger lambda
execute_check --> db: load tracker-queries
execute_check --> db: update tracker-queries
execute_check --> sns: trigger notification on state change
sns --> sns_email: send out email to subscribe

@enduml