@startuml c4-context-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", $sprite="person2", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_person_sprite-or-show_person_spritesprite")
System_Boundary(c1, "Gym Clas Tracker", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(app, "Application", "", $descr="Allows users track availability of a gym class", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}

System_Ext(gym, "Gym Application", "", $descr="Web Application of gym for course overview and course sign up", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")

Rel_D(user, app, "Set up tracking")
Rel_R(app, gym, "Get information about availability of gym class", "REST")
Rel_U(app, user, "Send tracking information", "Email")
Rel(user, gym, "Sign up to class")

@enduml